# Generated by Django 5.2.9 on 2025-12-16 03:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("organizations", "0001_initial"),
        ("requisitions", "0001_initial"),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RFPQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_number", models.PositiveSmallIntegerField()),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Short Text"),
                            ("TEXTAREA", "Long Text"),
                            ("SINGLE_CHOICE", "Single Choice"),
                            ("MULTI_CHOICE", "Multiple Choice"),
                            ("NUMBER", "Number"),
                            ("DATE", "Date"),
                            ("FILE", "File Upload"),
                            ("RATING", "Rating Scale"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="Options for choice-type questions",
                        null=True,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.0"), max_digits=5
                    ),
                ),
                (
                    "scoring_guidance",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Guidance for evaluators on how to score responses",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "RFP Question",
                "verbose_name_plural": "RFP Questions",
                "db_table": "rfp_question",
                "ordering": ["order", "question_number"],
            },
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "proposal_number",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("BAFO_REQUESTED", "BAFO Requested"),
                            ("BAFO_SUBMITTED", "BAFO Submitted"),
                            ("AWARDED", "Awarded"),
                            ("NOT_AWARDED", "Not Awarded"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("DISQUALIFIED", "Disqualified"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("revision_number", models.PositiveSmallIntegerField(default=1)),
                ("is_latest", models.BooleanField(default=True)),
                (
                    "technical_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "management_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "pricing_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposals",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal",
                "verbose_name_plural": "Proposals",
                "db_table": "proposal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RFP",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("EVALUATION", "Evaluation"),
                            ("BAFO", "BAFO Round"),
                            ("CLOSED", "Closed"),
                            ("AWARDED", "Awarded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "rfp_type",
                    models.CharField(
                        choices=[
                            ("SERVICES", "Services"),
                            ("GOODS", "Goods"),
                            ("COMBINED", "Combined"),
                        ],
                        default="SERVICES",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("publish_date", models.DateTimeField(blank=True, null=True)),
                ("question_deadline", models.DateTimeField(blank=True, null=True)),
                ("response_deadline", models.DateTimeField(blank=True, null=True)),
                ("evaluation_start_date", models.DateTimeField(blank=True, null=True)),
                ("award_target_date", models.DateField(blank=True, null=True)),
                (
                    "bidding_type",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("SEALED", "Sealed"),
                            ("MULTI_ROUND", "Multi-Round"),
                        ],
                        default="SEALED",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("INVITED", "Invited Only"), ("PUBLIC", "Public")],
                        default="INVITED",
                        max_length=20,
                    ),
                ),
                ("awarded_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "awarded_proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_for_rfp",
                        to="rfps.proposal",
                    ),
                ),
                (
                    "awarded_supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_rfps",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_rfps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfps",
                        to="organizations.organization",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfps",
                        to="requisitions.requisition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request for Proposal",
                "verbose_name_plural": "Requests for Proposal",
                "db_table": "rfp",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="proposal",
            name="rfp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to="rfps.rfp",
            ),
        ),
        migrations.CreateModel(
            name="BAFORound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("round_number", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True, default="")),
                (
                    "focus_areas",
                    models.JSONField(
                        blank=True,
                        help_text='Areas to focus on (e.g., ["pricing", "delivery"])',
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_bafo_rounds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rfp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bafo_rounds",
                        to="rfps.rfp",
                    ),
                ),
            ],
            options={
                "verbose_name": "BAFO Round",
                "verbose_name_plural": "BAFO Rounds",
                "db_table": "bafo_round",
                "ordering": ["round_number"],
            },
        ),
        migrations.CreateModel(
            name="RFPInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VIEWED", "Viewed"),
                            ("PROPOSAL_SUBMITTED", "Proposal Submitted"),
                            ("DECLINED", "Declined"),
                            ("DISQUALIFIED", "Disqualified"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "intent_to_bid",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YES", "Yes"),
                            ("NO", "No"),
                            ("UNDECIDED", "Undecided"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "decline_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("disqualified", models.BooleanField(default=False)),
                ("disqualification_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_rfp_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rfp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="rfps.rfp",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfp_invitations",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFP Invitation",
                "verbose_name_plural": "RFP Invitations",
                "db_table": "rfp_invitation",
                "ordering": ["-invited_at"],
            },
        ),
        migrations.CreateModel(
            name="RFPLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("line_number", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=500)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1"), max_digits=15
                    ),
                ),
                ("unit_of_measure", models.CharField(default="EA", max_length=20)),
                (
                    "target_unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfp_line_items",
                        to="catalog.item",
                    ),
                ),
                (
                    "rfp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="rfps.rfp",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFP Line Item",
                "verbose_name_plural": "RFP Line Items",
                "db_table": "rfp_line_item",
                "ordering": ["line_number"],
            },
        ),
        migrations.CreateModel(
            name="ProposalLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "extended_price",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=15
                    ),
                ),
                ("lead_time_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "part_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="rfps.proposal",
                    ),
                ),
                (
                    "rfp_line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposal_responses",
                        to="rfps.rfplineitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal Line Item",
                "verbose_name_plural": "Proposal Line Items",
                "db_table": "proposal_line_item",
            },
        ),
        migrations.CreateModel(
            name="RFPQA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True, default="")),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Private"),
                            ("PUBLIC", "Public"),
                            ("ALL_BIDDERS", "All Bidders"),
                        ],
                        default="PRIVATE",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answered_rfp_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asked_rfp_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rfp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_items",
                        to="rfps.rfp",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if internal question",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfp_questions",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFP Q&A",
                "verbose_name_plural": "RFP Q&A Items",
                "db_table": "rfp_qa",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer_text", models.TextField(blank=True, default="")),
                ("answer_choice", models.JSONField(blank=True, null=True)),
                (
                    "answer_number",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("answer_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_responses",
                        to="rfps.proposal",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="rfps.rfpquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Response",
                "verbose_name_plural": "Question Responses",
                "db_table": "question_response",
            },
        ),
        migrations.CreateModel(
            name="RFPSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("section_number", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=255)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATIVE", "Administrative"),
                            ("TECHNICAL", "Technical"),
                            ("MANAGEMENT", "Management"),
                            ("PRICING", "Pricing"),
                            ("TERMS", "Terms & Conditions"),
                            ("QUALIFICATIONS", "Qualifications"),
                        ],
                        default="TECHNICAL",
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Weight percentage for scoring (0-100)",
                        max_digits=5,
                    ),
                ),
                ("instructions", models.TextField(blank=True, default="")),
                ("is_scorable", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rfp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="rfps.rfp",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFP Section",
                "verbose_name_plural": "RFP Sections",
                "db_table": "rfp_section",
                "ordering": ["order", "section_number"],
            },
        ),
        migrations.AddField(
            model_name="rfpquestion",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="rfps.rfpsection",
            ),
        ),
        migrations.AddField(
            model_name="rfplineitem",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to pricing section",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="line_items",
                to="rfps.rfpsection",
            ),
        ),
        migrations.CreateModel(
            name="ProposalSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "section_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("evaluator_comments", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="rfps.proposal",
                    ),
                ),
                (
                    "rfp_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposal_sections",
                        to="rfps.rfpsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal Section",
                "verbose_name_plural": "Proposal Sections",
                "db_table": "proposal_section",
            },
        ),
        migrations.CreateModel(
            name="EvaluationTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LEAD", "Lead Evaluator"),
                            ("TECHNICAL", "Technical Evaluator"),
                            ("PRICING", "Pricing Evaluator"),
                            ("GENERAL", "General Evaluator"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_evaluators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfp_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rfp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_team",
                        to="rfps.rfp",
                    ),
                ),
                (
                    "assigned_sections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_evaluators",
                        to="rfps.rfpsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluation Team Member",
                "verbose_name_plural": "Evaluation Team Members",
                "db_table": "evaluation_team",
            },
        ),
        migrations.CreateModel(
            name="ScoringCriteria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight percentage (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.0"), max_digits=5
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_criteria",
                        to="rfps.scoringcriteria",
                    ),
                ),
                (
                    "rfp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="rfps.rfp",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scoring_criteria",
                        to="rfps.rfpsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scoring Criteria",
                "verbose_name_plural": "Scoring Criteria",
                "db_table": "scoring_criteria",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.0"), max_digits=5
                    ),
                ),
                ("comments", models.TextField(blank=True, default="")),
                ("is_final", models.BooleanField(default=False)),
                ("scored_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="given_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_scores",
                        to="rfps.proposal",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluation_scores",
                        to="rfps.rfpquestion",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluation_scores",
                        to="rfps.rfpsection",
                    ),
                ),
                (
                    "criteria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="rfps.scoringcriteria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluation Score",
                "verbose_name_plural": "Evaluation Scores",
                "db_table": "evaluation_score",
                "ordering": ["-scored_at"],
            },
        ),
        migrations.CreateModel(
            name="BAFOResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "response_data",
                    models.JSONField(
                        blank=True,
                        help_text="Revised pricing, terms, or other data",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bafo_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="rfps.baforound",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bafo_responses",
                        to="rfps.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "BAFO Response",
                "verbose_name_plural": "BAFO Responses",
                "db_table": "bafo_response",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bafo_round", "proposal"),
                        name="unique_bafo_round_proposal",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.UniqueConstraint(
                fields=("rfp", "supplier", "revision_number"),
                name="unique_rfp_supplier_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="baforound",
            constraint=models.UniqueConstraint(
                fields=("rfp", "round_number"), name="unique_rfp_bafo_round"
            ),
        ),
        migrations.AddConstraint(
            model_name="rfpinvitation",
            constraint=models.UniqueConstraint(
                fields=("rfp", "supplier"), name="unique_rfp_supplier_invitation"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposallineitem",
            constraint=models.UniqueConstraint(
                fields=("proposal", "rfp_line_item"), name="unique_proposal_line_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionresponse",
            constraint=models.UniqueConstraint(
                fields=("proposal", "question"),
                name="unique_proposal_question_response",
            ),
        ),
        migrations.AddConstraint(
            model_name="rfpsection",
            constraint=models.UniqueConstraint(
                fields=("rfp", "section_number"), name="unique_rfp_section_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="rfpquestion",
            constraint=models.UniqueConstraint(
                fields=("section", "question_number"),
                name="unique_section_question_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="rfplineitem",
            constraint=models.UniqueConstraint(
                fields=("rfp", "line_number"), name="unique_rfp_line_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposalsection",
            constraint=models.UniqueConstraint(
                fields=("proposal", "rfp_section"), name="unique_proposal_section"
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationteam",
            constraint=models.UniqueConstraint(
                fields=("rfp", "evaluator"), name="unique_rfp_evaluator"
            ),
        ),
    ]
