# Generated by Django 5.2.9 on 2025-12-18 23:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rbac_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("INTERNAL", "Internal User"), ("PORTAL", "Portal User")],
                default="INTERNAL",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="UserEmailPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_approval_required",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email when approval is required",
                    ),
                ),
                (
                    "email_approval_completed",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email when your submission is approved",
                    ),
                ),
                (
                    "email_approval_rejected",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email when your submission is rejected",
                    ),
                ),
                (
                    "email_contract_expiring",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email when contracts are expiring",
                    ),
                ),
                (
                    "email_bid_received",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email when bids are received on RFQs",
                    ),
                ),
                (
                    "email_goods_received",
                    models.BooleanField(
                        default=True, help_text="Receive email when goods are received"
                    ),
                ),
                (
                    "email_invoice_matched",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email when invoices are matched",
                    ),
                ),
                (
                    "email_document_submitted",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email when documents are submitted for review",
                    ),
                ),
                (
                    "email_budget_alert",
                    models.BooleanField(
                        default=True, help_text="Receive email for budget alerts"
                    ),
                ),
                (
                    "email_system_alert",
                    models.BooleanField(
                        default=True, help_text="Receive email for system alerts"
                    ),
                ),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("IMMEDIATE", "Immediate"),
                            ("DAILY", "Daily Digest"),
                            ("WEEKLY", "Weekly Digest"),
                            ("NONE", "No Emails"),
                        ],
                        default="IMMEDIATE",
                        help_text="How often to receive notification emails",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Email Preference",
                "verbose_name_plural": "User Email Preferences",
                "db_table": "user_email_preference",
            },
        ),
    ]
