# Generated by Django 5.2.9 on 2025-12-17 23:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("users", "0002_rbac_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this key", max_length=100
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        help_text="First 8 characters of the key (for identification)",
                        max_length=8,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        help_text="Hashed version of the full key", max_length=256
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        default=list,
                        help_text="List of permission scopes this key has access to",
                    ),
                ),
                (
                    "rate_limit",
                    models.PositiveIntegerField(
                        default=1000, help_text="Maximum requests per hour"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Leave empty for no expiration", null=True
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "db_table": "api_key",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalThreshold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("REQUISITION", "Requisition"),
                            ("PURCHASE_ORDER", "Purchase Order"),
                            ("INVOICE", "Invoice"),
                            ("CONTRACT", "Contract"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave empty for unlimited",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "auto_approve",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically approve without manual review",
                    ),
                ),
                (
                    "require_budget_check",
                    models.BooleanField(
                        default=True,
                        help_text="Check budget availability before approval",
                    ),
                ),
                (
                    "escalation_hours",
                    models.PositiveIntegerField(
                        default=24, help_text="Hours before escalation if not approved"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "escalation_role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Role to escalate to if not approved in time",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalated_thresholds",
                        to="users.role",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_thresholds",
                        to="organizations.organization",
                    ),
                ),
                (
                    "required_role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Role required to approve at this level",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_thresholds",
                        to="users.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Threshold",
                "verbose_name_plural": "Approval Thresholds",
                "db_table": "approval_threshold",
                "ordering": ["document_type", "min_amount"],
                "unique_together": {("organization", "document_type", "min_amount")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("APPROVAL_REQUIRED", "Approval Required"),
                            ("APPROVAL_COMPLETED", "Approval Completed"),
                            ("APPROVAL_REJECTED", "Approval Rejected"),
                            ("DOCUMENT_SUBMITTED", "Document Submitted"),
                            ("BID_RECEIVED", "Bid Received"),
                            ("CONTRACT_EXPIRING", "Contract Expiring"),
                            ("INVOICE_MATCHED", "Invoice Matched"),
                            ("GOODS_RECEIVED", "Goods Received"),
                            ("BUDGET_ALERT", "Budget Alert"),
                            ("SYSTEM_ALERT", "System Alert"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNREAD", "Unread"),
                            ("READ", "Read"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="UNREAD",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of related object (e.g., requisition, purchase_order)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "related_object_id",
                    models.UUIDField(
                        blank=True, help_text="ID of the related object", null=True
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="Frontend URL to navigate to",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data for the notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who will receive this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="notificatio_user_id_dae2a2_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="notificatio_user_id_26141b_idx",
                    ),
                    models.Index(
                        fields=["related_object_type", "related_object_id"],
                        name="notificatio_related_16ee33_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField(blank=True)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("STRING", "String"),
                            ("INTEGER", "Integer"),
                            ("DECIMAL", "Decimal"),
                            ("BOOLEAN", "Boolean"),
                            ("JSON", "JSON"),
                        ],
                        default="STRING",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Settings"),
                            ("NOTIFICATIONS", "Notification Settings"),
                            ("SECURITY", "Security Settings"),
                            ("WORKFLOW", "Workflow Settings"),
                            ("INTEGRATION", "Integration Settings"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Human-readable label", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this setting does"
                    ),
                ),
                (
                    "is_secret",
                    models.BooleanField(
                        default=False,
                        help_text="If true, value will be masked in responses",
                    ),
                ),
                (
                    "is_editable",
                    models.BooleanField(
                        default=True, help_text="If false, cannot be changed via API"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Preference",
                "verbose_name_plural": "System Preferences",
                "db_table": "system_preference",
                "ordering": ["category", "key"],
                "unique_together": {("organization", "key")},
            },
        ),
    ]
