# Generated by Django 5.2.9 on 2025-12-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="email_error",
            field=models.TextField(
                blank=True, help_text="Error message if email failed to send"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="email_sent",
            field=models.BooleanField(
                default=False, help_text="Whether email notification was sent"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="email_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="When email was sent", null=True
            ),
        ),
    ]
