# Generated by Django 5.2.9 on 2025-12-19 23:28

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_notification_email_error_notification_email_sent_and_more"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("APPROVAL_REQUIRED", "Approval Required"),
                    ("APPROVAL_COMPLETED", "Approval Completed"),
                    ("APPROVAL_REJECTED", "Approval Rejected"),
                    ("DOCUMENT_SUBMITTED", "Document Submitted"),
                    ("BID_RECEIVED", "Bid Received"),
                    ("CONTRACT_EXPIRING", "Contract Expiring"),
                    ("INVOICE_MATCHED", "Invoice Matched"),
                    ("GOODS_RECEIVED", "Goods Received"),
                    ("BUDGET_ALERT", "Budget Alert"),
                    ("SYSTEM_ALERT", "System Alert"),
                    ("RFP_PUBLISHED", "RFP Published"),
                    ("RFP_INVITATION", "RFP Invitation Received"),
                    ("RFP_DEADLINE_REMINDER", "RFP Deadline Reminder"),
                    ("RFP_QA_ANSWERED", "RFP Question Answered"),
                    ("PROPOSAL_RECEIVED", "Proposal Received"),
                    ("PROPOSAL_SHORTLISTED", "Proposal Shortlisted"),
                    ("PROPOSAL_AWARDED", "Proposal Awarded"),
                    ("PROPOSAL_NOT_AWARDED", "Proposal Not Awarded"),
                    ("BAFO_REQUESTED", "BAFO Requested"),
                    ("BAFO_RECEIVED", "BAFO Response Received"),
                    ("RFP_EVALUATION_COMPLETE", "RFP Evaluation Complete"),
                    ("RFP_CLOSED", "RFP Closed"),
                    ("RFQ_PUBLISHED", "RFQ Published"),
                    ("RFQ_INVITATION", "RFQ Invitation Received"),
                    ("RFQ_DEADLINE_REMINDER", "RFQ Deadline Reminder"),
                    ("QUOTE_RECEIVED", "Quote Received"),
                    ("RFQ_AWARDED", "RFQ Awarded"),
                    ("RFQ_CLOSED", "RFQ Closed"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "object_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of object (e.g., requisition, rfq, rfp, po)",
                        max_length=50,
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID of the related object"
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=apps.core.models.attachment_upload_path),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "db_table": "attachment",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="attachment_object__019a07_idx",
                    ),
                    models.Index(
                        fields=["uploaded_by", "uploaded_at"],
                        name="attachment_uploade_9721d1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "object_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of object (e.g., requisition, rfq, rfp, po)",
                        max_length=50,
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID of the related object"
                    ),
                ),
                ("content", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="core.comment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "db_table": "comment",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="comment_object__300d32_idx",
                    ),
                    models.Index(
                        fields=["author", "created_at"],
                        name="comment_author__096cf7_idx",
                    ),
                ],
            },
        ),
    ]
