# Generated by Django 5.2.9 on 2025-12-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfqs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfq",
            name="bid_type",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open Bid"),
                    ("SEALED", "Sealed Bid"),
                    ("INVITED", "Invited Bid"),
                ],
                default="INVITED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rfq",
            name="buyer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="rfq",
            name="buyer_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="rfq",
            name="buyer_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="rfq",
            name="contract_duration_months",
            field=models.PositiveIntegerField(
                blank=True, help_text="Proposed contract length in months", null=True
            ),
        ),
        migrations.AddField(
            model_name="rfq",
            name="contract_renewal_options",
            field=models.CharField(
                blank=True, help_text='e.g., "2 x 1-year renewals"', max_length=200
            ),
        ),
        migrations.AddField(
            model_name="rfq",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="rfq",
            name="delivery_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rfq",
            name="delivery_terms",
            field=models.CharField(
                blank=True, help_text="Incoterms (e.g., FOB, CIF, DDP)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="rfq",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="rfq",
            name="evaluation_criteria",
            field=models.JSONField(
                blank=True,
                help_text='Weighted scoring criteria, e.g., [{"name": "Price", "weight": 60}, {"name": "Quality", "weight": 20}]',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rfq",
            name="expected_award_date",
            field=models.DateTimeField(
                blank=True, help_text="Target date for announcing the winner", null=True
            ),
        ),
        migrations.AddField(
            model_name="rfq",
            name="issue_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfq",
            name="nda_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rfq",
            name="payment_terms",
            field=models.CharField(
                choices=[
                    ("NET15", "Net 15"),
                    ("NET30", "Net 30"),
                    ("NET45", "Net 45"),
                    ("NET60", "Net 60"),
                    ("NET90", "Net 90"),
                    ("DUE_ON_RECEIPT", "Due on Receipt"),
                    ("ADVANCE", "50% Advance, 50% on Delivery"),
                    ("MILESTONE", "Milestone-based"),
                    ("OTHER", "Other"),
                ],
                default="NET30",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rfq",
            name="payment_terms_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rfq",
            name="project_background",
            field=models.TextField(
                blank=True,
                help_text="Brief summary of the project goals to provide context",
            ),
        ),
        migrations.AddField(
            model_name="rfq",
            name="qa_deadline",
            field=models.DateTimeField(
                blank=True, help_text="Deadline for supplier questions", null=True
            ),
        ),
        migrations.AddField(
            model_name="rfq",
            name="required_attachments_description",
            field=models.TextField(
                blank=True,
                help_text="Description of required attachments (licenses, NDAs, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="rfq",
            name="required_certifications",
            field=models.TextField(
                blank=True,
                help_text="Required vendor certifications (e.g., ISO 9001, SOC 2)",
            ),
        ),
        migrations.AddField(
            model_name="rfq",
            name="required_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfq",
            name="submission_deadline",
            field=models.DateTimeField(
                blank=True, help_text="Final deadline for bid submissions", null=True
            ),
        ),
        migrations.AddField(
            model_name="rfq",
            name="terms_and_conditions",
            field=models.TextField(blank=True),
        ),
    ]
