# Generated by Django 5.2.9 on 2025-12-16 01:21

import datetime
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budget", "0001_initial"),
        ("organizations", "0001_initial"),
        ("purchase_orders", "0002_poline_quantity_invoiced_purchaseorder_encumbrance"),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "supplier_invoice_number",
                    models.CharField(
                        help_text="Supplier invoice reference number", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("VALIDATED", "Validated"),
                            ("MATCHED", "Matched"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                            ("DISPUTED", "Disputed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AUTO", "Automatic Match"),
                            ("MANUAL", "Manual Match"),
                            ("OVERRIDE", "Override Match"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("invoice_date", models.DateField(default=datetime.date.today)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("dispute_reason", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encumbrance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Encumbrance to liquidate on approval",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="budget.encumbrance",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="organizations.organization",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="purchase_orders.purchaseorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("line_number", models.PositiveIntegerField(default=1)),
                (
                    "quantity_invoiced",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("MATCHED", "Matched"),
                            ("QUANTITY_MISMATCH", "Quantity Mismatch"),
                            ("PRICE_MISMATCH", "Price Mismatch"),
                            ("BOTH_MISMATCH", "Both Mismatch"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "quantity_variance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Invoice qty - GR qty",
                        max_digits=12,
                    ),
                ),
                (
                    "price_variance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Invoice price - PO price",
                        max_digits=12,
                    ),
                ),
                (
                    "quantity_matched",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Quantity successfully matched",
                        max_digits=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "po_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_lines",
                        to="purchase_orders.poline",
                    ),
                ),
            ],
            options={
                "ordering": ["line_number"],
            },
        ),
        migrations.CreateModel(
            name="MatchingConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_tolerance_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Max price variance % for auto-match (default 5%)",
                        max_digits=5,
                    ),
                ),
                (
                    "quantity_tolerance_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="Max quantity variance % for auto-match (default 2%)",
                        max_digits=5,
                    ),
                ),
                (
                    "auto_match_max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10000.00"),
                        help_text="Max invoice total for auto-match (default $10,000)",
                        max_digits=12,
                    ),
                ),
                (
                    "require_goods_receipt",
                    models.BooleanField(
                        default=True,
                        help_text="Require GR before invoice can be matched",
                    ),
                ),
                (
                    "allow_over_receipt",
                    models.BooleanField(
                        default=False, help_text="Allow receipt qty to exceed PO qty"
                    ),
                ),
                (
                    "allow_over_invoice",
                    models.BooleanField(
                        default=False, help_text="Allow invoice qty to exceed PO qty"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_config",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matching Configuration",
                "verbose_name_plural": "Matching Configurations",
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "status"], name="invoices_in_organiz_01efe4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["purchase_order"], name="invoices_in_purchas_f75298_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["supplier"], name="invoices_in_supplie_438081_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["number"], name="invoices_in_number_9bae8b_idx"),
        ),
        migrations.AddIndex(
            model_name="invoiceline",
            index=models.Index(
                fields=["invoice", "match_status"],
                name="invoices_in_invoice_d2fb52_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoiceline",
            unique_together={("invoice", "line_number")},
        ),
    ]
