# Generated by Django 5.2.9 on 2025-12-16 02:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditConfiguration",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="audit_config",
                        serialize=False,
                        to="organizations.organization",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable audit logging for this organization",
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="Number of days to retain audit logs (0 = forever)",
                    ),
                ),
                (
                    "track_field_changes",
                    models.BooleanField(
                        default=True,
                        help_text="Track individual field changes in audit logs",
                    ),
                ),
                (
                    "excluded_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of field names to exclude from change tracking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Configuration",
                "verbose_name_plural": "Audit Configurations",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("object_id", models.UUIDField()),
                (
                    "object_repr",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("STATE_TRANSITION", "State Transition"),
                            ("SOFT_DELETE", "Soft Delete"),
                            ("RESTORE", "Restore"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_state", models.CharField(blank=True, default="", max_length=50)),
                ("to_state", models.CharField(blank=True, default="", max_length=50)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_audit_content_4c2ead_idx",
                    ),
                    models.Index(
                        fields=["organization", "timestamp"],
                        name="audit_audit_organiz_47f094_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_audit_user_id_e8be02_idx",
                    ),
                    models.Index(
                        fields=["action"], name="audit_audit_action_86e815_idx"
                    ),
                ],
            },
        ),
    ]
