# Generated by Django 5.2.9 on 2025-12-16 02:16

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentConfiguration",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="document_config",
                        serialize=False,
                        to="organizations.organization",
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.PositiveIntegerField(
                        default=10, help_text="Maximum file size in MB"
                    ),
                ),
                (
                    "allowed_extensions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed file extensions (empty = all allowed)",
                    ),
                ),
                (
                    "require_document_type",
                    models.BooleanField(
                        default=False,
                        help_text="Require document type to be specified on upload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Configuration",
                "verbose_name_plural": "Document Configurations",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the document", max_length=255
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename when uploaded", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of the document",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.documents.models.document_upload_path
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Document"),
                            ("EXCEL", "Excel Spreadsheet"),
                            ("WORD", "Word Document"),
                            ("IMAGE", "Image"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CONTRACT", "Contract"),
                            ("INVOICE", "Invoice"),
                            ("QUOTE", "Quote/Quotation"),
                            ("SPECIFICATION", "Specification"),
                            ("CERTIFICATE", "Certificate"),
                            ("PHOTO", "Photo/Image"),
                            ("REPORT", "Report"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, help_text="Whether this is the current version"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="organizations.organization",
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_versions",
                        to="documents.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-upload_date"],
                "indexes": [
                    models.Index(
                        fields=["organization", "upload_date"],
                        name="documents_d_organiz_428f7c_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="documents_d_content_ba3031_idx",
                    ),
                    models.Index(
                        fields=["document_type"], name="documents_d_documen_40c475_idx"
                    ),
                    models.Index(
                        fields=["is_current"], name="documents_d_is_curr_fe24da_idx"
                    ),
                ],
            },
        ),
    ]
