# Generated by Django 5.2.9 on 2025-12-16 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
        ("purchase_orders", "0002_poline_quantity_invoiced_purchaseorder_encumbrance"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                help_text="Contract this PO is placed against",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="contracts.contract",
            ),
        ),
    ]
