# Generated by Django 5.2.9 on 2025-12-18 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0003_purchaseorder_contract"),
        ("requisitions", "0002_add_requisition_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="poline",
            name="requisition_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Source requisition line this PO line was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="po_lines",
                to="requisitions.requisitionline",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="requisition",
            field=models.ForeignKey(
                blank=True,
                help_text="Source requisition this PO was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="requisitions.requisition",
            ),
        ),
    ]
