# Generated by Django 5.2.9 on 2025-12-18 23:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0004_add_requisition_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="POAcknowledgment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        help_text="Acknowledgment status",
                        max_length=20,
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the supplier acknowledged the PO",
                        null=True,
                    ),
                ),
                (
                    "revised_delivery_date",
                    models.DateField(
                        blank=True,
                        help_text="Supplier proposed delivery date (if different from PO)",
                        null=True,
                    ),
                ),
                (
                    "delivery_date_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for revised delivery date",
                        max_length=500,
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Supplier comments or notes"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection (if status is REJECTED)",
                    ),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When last acknowledgment reminder was sent",
                        null=True,
                    ),
                ),
                (
                    "reminders_sent",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of reminder emails sent"
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Portal user who acknowledged",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="po_acknowledgments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.OneToOneField(
                        help_text="Purchase order being acknowledged",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgment",
                        to="purchase_orders.purchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "PO Acknowledgment",
                "verbose_name_plural": "PO Acknowledgments",
                "db_table": "po_acknowledgment",
                "ordering": ["-created_at"],
            },
        ),
    ]
