# Generated by Django 5.2.9 on 2025-12-19 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0005_poacknowledgment"),
        ("rfps", "0002_add_rfp_enhancements"),
    ]

    operations = [
        migrations.AddField(
            model_name="poline",
            name="proposal_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Source proposal line this PO line was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="po_lines",
                to="rfps.proposallineitem",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="proposal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="rfps.proposal",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="rfp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="rfps.rfp",
            ),
        ),
    ]
