# Generated by Django 5.2.9 on 2025-12-18 23:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address to send invitation to", max_length=254
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique token for accepting the invitation",
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("EXPIRED", "Expired"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING",
                        help_text="Current invitation status",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this invitation expires"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invitation was accepted",
                        null=True,
                    ),
                ),
                (
                    "personal_message",
                    models.TextField(
                        blank=True, help_text="Optional personal message from inviter"
                    ),
                ),
                (
                    "accepted_by_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User account created when accepting",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_portal_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Internal user who created this invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_invitations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Supplier being invited to the portal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_invitations",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal Invitation",
                "verbose_name_plural": "Portal Invitations",
                "db_table": "portal_invitation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortalUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Admin"),
                            ("MEMBER", "Member"),
                        ],
                        default="MEMBER",
                        help_text="Role within the supplier organization",
                        max_length=20,
                    ),
                ),
                (
                    "access_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="ACTIVE",
                        help_text="Current access status",
                        max_length=20,
                    ),
                ),
                (
                    "invited_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the invitation was created"
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, help_text="Last portal login timestamp", null=True
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Internal user who invited this portal user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Supplier this portal user belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_users",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Authentication user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal User",
                "verbose_name_plural": "Portal Users",
                "db_table": "portal_user",
                "ordering": ["-created_at"],
            },
        ),
    ]
