# Generated by Django 5.2.9 on 2025-12-30 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0002_portalinvitation_portaluser"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="cost_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Order fulfillment/cost score (0-100)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="delivery_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="On-time delivery score (0-100)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_preferred",
            field=models.BooleanField(default=False, help_text="Preferred vendor flag"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="overall_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Overall performance score (0-100)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="performance_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STRATEGIC", "Strategic Partner"),
                    ("PREFERRED", "Preferred"),
                    ("APPROVED", "Approved"),
                    ("CONDITIONAL", "Conditional"),
                    ("PROBATION", "Probation"),
                ],
                help_text="Performance tier based on overall score",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="quality_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Invoice accuracy/quality score (0-100)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="scores_calculated_at",
            field=models.DateTimeField(
                blank=True, help_text="When scores were last calculated", null=True
            ),
        ),
    ]
