# Generated by Django 5.2.9 on 2025-12-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfp",
            name="budget_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum budget range",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rfp",
            name="budget_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum budget range",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rfp",
            name="confidentiality_terms",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Confidentiality and data protection requirements",
            ),
        ),
        migrations.AddField(
            model_name="rfp",
            name="contract_end_date",
            field=models.DateField(
                blank=True, help_text="Expected contract end date", null=True
            ),
        ),
        migrations.AddField(
            model_name="rfp",
            name="contract_start_date",
            field=models.DateField(
                blank=True, help_text="Expected contract start date", null=True
            ),
        ),
        migrations.AddField(
            model_name="rfp",
            name="currency",
            field=models.CharField(
                default="USD",
                help_text="Currency code (e.g., USD, EUR, GBP)",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="rfp",
            name="current_state_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Description of current pain points and challenges",
            ),
        ),
        migrations.AddField(
            model_name="rfp",
            name="executive_summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="High-level overview of the RFP purpose and goals",
            ),
        ),
        migrations.AddField(
            model_name="rfp",
            name="future_state_goals",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Vision of desired outcomes and success criteria",
            ),
        ),
        migrations.AddField(
            model_name="rfp",
            name="insurance_requirements",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Required insurance coverage and limits",
            ),
        ),
        migrations.AddField(
            model_name="rfp",
            name="ip_ownership",
            field=models.CharField(
                choices=[
                    ("CLIENT", "Client Owns All IP"),
                    ("VENDOR", "Vendor Retains IP"),
                    ("SHARED", "Shared/Licensed"),
                    ("NEGOTIABLE", "To Be Negotiated"),
                ],
                default="CLIENT",
                help_text="Intellectual property ownership terms",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rfp",
            name="nda_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether NDA is required before viewing RFP details",
            ),
        ),
        migrations.AddField(
            model_name="rfp",
            name="organization_context",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Company mission, values, strategic alignment",
            ),
        ),
        migrations.AddField(
            model_name="rfp",
            name="payment_terms",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Payment terms (e.g., NET30, NET60)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="rfp",
            name="qa_session_date",
            field=models.DateTimeField(
                blank=True, help_text="Date for Q&A session with vendors", null=True
            ),
        ),
        migrations.AddField(
            model_name="rfp",
            name="shortlist_announcement_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when shortlisted vendors will be announced",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rfpquestion",
            name="attachment_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Expected file type (e.g., PDF, Excel, Word)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="rfpquestion",
            name="is_mandatory_attachment",
            field=models.BooleanField(
                default=False,
                help_text="If True, this is a required document/attachment for compliance",
            ),
        ),
        migrations.AddField(
            model_name="rfpquestion",
            name="min_attachments",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Minimum number of attachments required"
            ),
        ),
    ]
