# Generated by Django 5.2.9 on 2025-12-18 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("requisitions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequisitionTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("department", models.CharField(max_length=50)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="If true, all users in the organization can use this template",
                    ),
                ),
                ("use_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_requisition_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisition_templates",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisition Template",
                "verbose_name_plural": "Requisition Templates",
                "db_table": "requisition_template",
                "ordering": ["-use_count", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RequisitionTemplateLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.CharField(max_length=500)),
                ("quantity", models.CharField(default="1", max_length=20)),
                ("unit_of_measure", models.CharField(default="EA", max_length=20)),
                (
                    "estimated_unit_price",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="requisitions.requisitiontemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisition Template Line",
                "verbose_name_plural": "Requisition Template Lines",
                "db_table": "requisition_template_line",
                "ordering": ["id"],
            },
        ),
    ]
