# Generated by Django 5.2.9 on 2025-12-16 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDefinition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("SPEND_ANALYSIS", "Spend Analysis"),
                            ("SUPPLIER_PERFORMANCE", "Supplier Performance"),
                            ("BUDGET_UTILIZATION", "Budget Utilization"),
                            ("PO_CYCLE_TIME", "PO Cycle Time"),
                            ("CONTRACT_EXPIRATION", "Contract Expiration"),
                            ("RFX_ANALYTICS", "RFx Analytics"),
                            ("INVOICE_MATCHING", "Invoice Matching"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "available_filters",
                    models.JSONField(
                        default=dict,
                        help_text="JSON dict of available filter configurations",
                    ),
                ),
                (
                    "available_columns",
                    models.JSONField(
                        default=list,
                        help_text="JSON list of available column definitions",
                    ),
                ),
                (
                    "default_columns",
                    models.JSONField(
                        default=list, help_text="JSON list of default column selections"
                    ),
                ),
                (
                    "service_class",
                    models.CharField(
                        help_text="Python path to service class (e.g., apps.reports.services.spend_service.SpendAnalysisService)",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Report Definition",
                "verbose_name_plural": "Report Definitions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "filters",
                    models.JSONField(
                        default=dict,
                        help_text="JSON dict of user-selected filter values",
                    ),
                ),
                (
                    "columns",
                    models.JSONField(
                        default=list, help_text="JSON list of user-selected columns"
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="If true, visible to all users in the organization",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="saved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_reports",
                        to="organizations.organization",
                    ),
                ),
                (
                    "report_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="saved_reports",
                        to="reports.reportdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Report",
                "verbose_name_plural": "Saved Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="0-6 (Monday-Sunday), for weekly schedules",
                        null=True,
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="1-31, for monthly schedules", null=True
                    ),
                ),
                ("time_of_day", models.TimeField()),
                (
                    "export_format",
                    models.CharField(
                        choices=[("EXCEL", "Excel"), ("CSV", "CSV"), ("PDF", "PDF")],
                        max_length=10,
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        default=list, help_text="JSON list of email addresses"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "saved_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reports.savedreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Report",
                "verbose_name_plural": "Scheduled Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardKPI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kpi_type",
                    models.CharField(
                        choices=[
                            ("TOTAL_SPEND_MTD", "Total Spend MTD"),
                            ("TOTAL_SPEND_YTD", "Total Spend YTD"),
                            ("BUDGET_UTILIZATION", "Budget Utilization %"),
                            ("CONTRACT_COMPLIANCE", "Contract Compliance %"),
                            ("MAVERICK_SPEND", "Maverick Spend %"),
                            ("OPEN_RFX_COUNT", "Open RFx Count"),
                            ("PENDING_APPROVALS", "Pending Approvals"),
                            ("AVG_PO_CYCLE_TIME", "Avg PO Cycle Time Days"),
                            ("SUPPLIER_PERFORMANCE_AVG", "Avg Supplier Performance"),
                            ("EXPIRING_CONTRACTS_90D", "Expiring Contracts 90 Days"),
                            ("INVOICE_MATCH_RATE", "Invoice Match Rate %"),
                            ("ON_TIME_DELIVERY_RATE", "On-Time Delivery Rate %"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "numeric_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="For monetary amounts",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "percentage_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="For percentages (0-100)",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "count_value",
                    models.PositiveIntegerField(
                        blank=True, help_text="For counts", null=True
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Previous period value for trend comparison",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage change from previous period",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_kpis",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard KPI",
                "verbose_name_plural": "Dashboard KPIs",
                "indexes": [
                    models.Index(
                        fields=["organization", "kpi_type", "-calculated_at"],
                        name="reports_das_organiz_2f4cf2_idx",
                    )
                ],
                "unique_together": {
                    ("organization", "kpi_type", "period_start", "period_end")
                },
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filters_used", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cached_result",
                    models.JSONField(
                        blank=True,
                        help_text="Cached report data for smaller reports",
                        null=True,
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        help_text="File path for exported reports",
                        null=True,
                        upload_to="reports/exports/",
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "cache_key",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_executions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "report_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="reports.reportdefinition",
                    ),
                ),
                (
                    "saved_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="reports.savedreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Execution",
                "verbose_name_plural": "Report Executions",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "cache_key"],
                        name="reports_rep_organiz_643833_idx",
                    ),
                    models.Index(
                        fields=["status", "started_at"],
                        name="reports_rep_status_dd0810_idx",
                    ),
                ],
            },
        ),
    ]
