# Generated by Django 5.2.9 on 2025-12-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardkpi",
            name="kpi_type",
            field=models.CharField(
                choices=[
                    ("TOTAL_SPEND_MTD", "Total Spend MTD"),
                    ("TOTAL_SPEND_YTD", "Total Spend YTD"),
                    ("BUDGET_UTILIZATION", "Budget Utilization %"),
                    ("CONTRACT_COMPLIANCE", "Contract Compliance %"),
                    ("MAVERICK_SPEND", "Maverick Spend %"),
                    ("OPEN_RFX_COUNT", "Open RFx Count"),
                    ("PENDING_APPROVALS", "Pending Approvals"),
                    ("AVG_PO_CYCLE_TIME", "Avg PO Cycle Time Days"),
                    ("SUPPLIER_PERFORMANCE_AVG", "Avg Supplier Performance"),
                    ("EXPIRING_CONTRACTS_90D", "Expiring Contracts 90 Days"),
                    ("INVOICE_MATCH_RATE", "Invoice Match Rate %"),
                    ("ON_TIME_DELIVERY_RATE", "On-Time Delivery Rate %"),
                    ("RFP_OPEN_COUNT", "Open RFPs"),
                    ("RFP_PROPOSALS_RECEIVED", "Proposals Received"),
                    ("RFP_AVG_EVALUATION_SCORE", "Avg Evaluation Score"),
                    ("RFP_BAFO_ROUNDS_ACTIVE", "Active BAFO Rounds"),
                    ("RFP_TIME_TO_AWARD_AVG", "Avg Time to Award Days"),
                    ("RFP_SUPPLIER_RESPONSE_RATE", "Supplier Response Rate %"),
                    ("RFP_EVALUATION_COMPLETION_RATE", "Evaluation Completion Rate %"),
                    ("RFP_AWARDED_VALUE_MTD", "RFP Awarded Value MTD"),
                    ("RFP_AWARDED_VALUE_YTD", "RFP Awarded Value YTD"),
                ],
                max_length=50,
            ),
        ),
    ]
