# Generated by Django 5.2.9 on 2025-12-16 02:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("organizations", "0001_initial"),
        ("purchase_orders", "0002_poline_quantity_invoiced_purchaseorder_encumbrance"),
        ("rfqs", "0001_initial"),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.CharField(blank=True, max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("BLANKET", "Blanket Order"),
                            ("FIXED_PRICE", "Fixed Price"),
                            ("TIME_MATERIALS", "Time & Materials"),
                            ("FRAMEWORK", "Framework Agreement"),
                        ],
                        default="BLANKET",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Maximum contract value",
                        max_digits=15,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("auto_renew", models.BooleanField(default=False)),
                (
                    "renewal_notice_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Days before expiry to send renewal notice",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("NET15", "Net 15"),
                            ("NET30", "Net 30"),
                            ("NET45", "Net 45"),
                            ("NET60", "Net 60"),
                            ("NET90", "Net 90"),
                            ("DUE_ON_RECEIPT", "Due on Receipt"),
                            ("ADVANCE", "Advance Payment"),
                        ],
                        default="NET30",
                        max_length=20,
                    ),
                ),
                ("terms_and_conditions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("terminated_at", models.DateTimeField(blank=True, null=True)),
                ("termination_reason", models.TextField(blank=True)),
                ("amendment_number", models.PositiveIntegerField(default=0)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent_contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original contract if this is an amendment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amendments",
                        to="contracts.contract",
                    ),
                ),
                (
                    "rfq",
                    models.ForeignKey(
                        blank=True,
                        help_text="RFQ this contract was created from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to="rfqs.rfq",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "db_table": "contract",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("MISSED", "Missed"),
                            ("WAIVED", "Waived"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Payment amount tied to this milestone",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Milestone",
                "verbose_name_plural": "Contract Milestones",
                "db_table": "contract_milestone",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="ContractLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("line_number", models.PositiveIntegerField(default=1)),
                ("description", models.CharField(max_length=500)),
                ("unit_of_measure", models.CharField(default="EA", max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "min_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=500)),
                (
                    "catalog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_lines",
                        to="catalog.item",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Line",
                "verbose_name_plural": "Contract Lines",
                "db_table": "contract_line",
                "ordering": ["line_number"],
                "unique_together": {("contract", "line_number")},
            },
        ),
        migrations.CreateModel(
            name="ContractSpend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=500)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spend_records",
                        to="contracts.contract",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_spend_records",
                        to="purchase_orders.purchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Spend",
                "verbose_name_plural": "Contract Spend Records",
                "db_table": "contract_spend",
                "ordering": ["-recorded_at"],
                "unique_together": {("contract", "purchase_order")},
            },
        ),
    ]
