# Generated by Django 5.2.9 on 2025-12-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="last_renewal_alert_sent",
            field=models.DateTimeField(
                blank=True,
                help_text="When the last renewal alert was sent (for deduplication)",
                null=True,
            ),
        ),
    ]
