# Generated by Django 5.2.9 on 2025-12-19 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contract_last_renewal_alert_sent"),
        ("rfps", "0002_add_rfp_enhancements"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="proposal",
            field=models.ForeignKey(
                blank=True,
                help_text="Proposal this contract was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="rfps.proposal",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="rfp",
            field=models.ForeignKey(
                blank=True,
                help_text="RFP this contract was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="rfps.rfp",
            ),
        ),
    ]
