# Generated by Django 5.2.9 on 2025-12-15 22:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("FROZEN", "Frozen"),
                            ("CLOSED", "Closed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="budget.budgetline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Line",
                "verbose_name_plural": "Budget Lines",
                "db_table": "budget_line",
            },
        ),
        migrations.CreateModel(
            name="Encumbrance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("REQUISITION", "Requisition"),
                            ("PO", "Purchase Order"),
                            ("INVOICE", "Invoice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference_id", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RELEASED", "Released"),
                            ("LIQUIDATED", "Liquidated"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("liquidated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "budget_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encumbrances",
                        to="budget.budgetline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encumbrance",
                "verbose_name_plural": "Encumbrances",
                "db_table": "encumbrance",
            },
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("year", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiscal_years",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Year",
                "verbose_name_plural": "Fiscal Years",
                "db_table": "fiscal_year",
                "unique_together": {("organization", "year")},
            },
        ),
        migrations.AddField(
            model_name="budgetline",
            name="fiscal_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_lines",
                to="budget.fiscalyear",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="budgetline",
            unique_together={("fiscal_year", "code")},
        ),
    ]
